#!/bin/bash
# Script para configurar PipeWire para headsets Redragon sem fio
# Detecta automaticamente o dispositivo e gera a configuração

set -e

# Cores
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${YELLOW}ℹ${NC} $1"
}

echo "Configurador PipeWire para Headsets Redragon"
echo "=============================================="
echo

# Verificar se PipeWire está rodando
if ! pgrep -x "pipewire" > /dev/null; then
    print_error "PipeWire não está rodando!"
    exit 1
fi

print_success "PipeWire detectado"

# Detectar sink do headset Redragon
print_info "Detectando headset Redragon..."
SINK=""

# Lista de padrões para detectar
PATTERNS=(
    "XiiSound.*H[0-9]{3}"
    "Weltrend.*Wireless"
    "Redragon.*Wireless"
    "XiiSound.*Wireless"
)

# Procura por sinks que correspondam aos padrões
for pattern in "${PATTERNS[@]}"; do
    SINK=$(pactl list sinks short | grep -E "$pattern" | grep -oP 'alsa_output\.[^\s]+' | head -n 1)
    if [ -n "$SINK" ]; then
        break
    fi
done

if [ -z "$SINK" ]; then
    print_error "Nenhum headset Redragon detectado!"
    echo
    echo "Sinks disponíveis:"
    pactl list sinks short
    echo
    echo "Se o seu headset está na lista acima, por favor:"
    echo "1. Abra uma issue no repositório"
    echo "2. Inclua a saída do comando: pactl list sinks short"
    exit 1
fi

print_success "Headset detectado: $SINK"

# Extrair informações do dispositivo
DEVICE_DESC=$(pactl list sinks | grep -A 10 "$SINK" | grep "Description:" | sed 's/.*Description: //')
print_info "Dispositivo: $DEVICE_DESC"

# Criar diretório de configuração
PIPEWIRE_CONF_DIR="$HOME/.config/pipewire/pipewire.conf.d"
mkdir -p "$PIPEWIRE_CONF_DIR"

# Gerar arquivo de configuração
CONF_FILE="$PIPEWIRE_CONF_DIR/redragon-headset.conf"

cat > "$CONF_FILE" <<EOF
# PipeWire configuration for Redragon Wireless Headsets
# Auto-generated by configure-pipewire.sh
#
# Device: $DEVICE_DESC
# Sink: $SINK
#
# This configuration forces hardware volume control for Redragon headsets
# to ensure proper audio routing to both channels.

# Enable hardware volume control
context.properties = {
    # Use ALSA PCM controls directly
    alsa.mixer.control = "PCM"
}

# Optional: Set initial volume to 100% on device connection
# Uncomment if needed:
#
# context.exec = [
#     {
#         path = "pactl"
#         args = "set-sink-volume $SINK 100%"
#     }
# ]
EOF

print_success "Configuração criada: $CONF_FILE"

# Perguntar se deseja aplicar
echo
read -p "Deseja aplicar a configuração agora? (requer reiniciar PipeWire) (s/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[SsYy]$ ]]; then
    print_info "Reiniciando PipeWire..."
    systemctl --user restart pipewire pipewire-pulse wireplumber 2>/dev/null || {
        systemctl --user restart pipewire pipewire-pulse
    }
    sleep 2
    print_success "PipeWire reiniciado!"

    echo
    print_info "Verificando configuração..."
    if systemctl --user is-active pipewire > /dev/null; then
        print_success "PipeWire está rodando corretamente"
        echo
        echo "Configuração aplicada com sucesso!"
        echo
        echo "Use 'redragon-volume' para controlar o volume:"
        echo "  redragon-volume 75    # Define para 75%"
        echo "  redragon-volume up    # Aumenta 5%"
        echo "  redragon-volume down  # Diminui 5%"
    else
        print_error "Erro ao reiniciar PipeWire"
        echo "Você pode tentar manualmente:"
        echo "  systemctl --user restart pipewire pipewire-pulse"
    fi
else
    print_info "Para aplicar manualmente depois:"
    echo "  systemctl --user restart pipewire pipewire-pulse"
fi

echo
echo "Para desfazer, remova o arquivo:"
echo "  rm $CONF_FILE"
echo "  systemctl --user restart pipewire pipewire-pulse"
